// Allowance ===>
//export const ADD_ALLOWANCE_TO_DB = "ADD_ALLOWANCE_TO_DB";


//User
export const RECEIVE_LOGGED_USER = "RECEIVE_LOGGED_USER"
export const USER_LOGOUT = " USER_LOGOUT"


//Allowances
export const RECEIVE_ALLOWANCES = "RECEIVE_ALLOWANCES"
export const RECEIVE_ADMIN_ALLOWANCES = "ECEIVE_ADMIN_ALLOWANCES"
export const RECEIVE_PENDING_ALLOWANCES = "RECEIVE_PENDING_ALLOWANCES"
export const RECEIVE_ACTIVE_ALLOWANCES = "RECEIVE_ACTIVE_ALLOWANCES"
export const RECEIVE_HISTORY_ALLOWANCES = "RECEIVE_HISTORY_ALLOWANCES"
export const RECEIVE_BOOK_ALLOWANCES = "RECEIVE_BOOK_ALLOWANCES"

// DisciplineEvents
export const RECEIVE_EVENT_LIST = "RECEIVE_EVENT_LIST"
export const RECEIVE_TECH_LIST = "RECEIVE_TECH_LIST"

// NavBar 
export const SET_OPEN_CLOSE_NAVBAR = "SET_OPEN_CLOSE_NAVBAR"

// Home office
export const RECEIVE_HOME_OFFICE_LIST = "RECEIVE_HOME_OFFICE_LIST"
export const RECEIVE_HOME_OFFICE_BIRTHDAY_LIST = "RECEIVE_HOME_OFFICE_BIRTHDAY_LIST"